name: Docker Build

on:
  pull_request:
  push:
    branches: [ latest ]
  schedule:
    - cron: '0 0 * * 0,4'

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: arifjenong
          password: ${{ secrets.DOCKER_HUB }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./
          file: ./Dockerfile
          run: echo ${{ secrets.RCLONE_CONFIG }} > ~/.config/rclone/rclone.conf
          run: rclone copy znxtproject:ccache/lineage-19.1/ccache.tar.gz ~/znxt -P
          push: true
          tags: arifjenong/lineage:latest


      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}